######################################################################
# Automatically generated by qmake (3.0) ons jan. 11 20:04:16 2017
######################################################################

TEMPLATE = lib
TARGET = ooura
INCLUDEPATH += .

unix:QMAKE_CXXFLAGS += -std=c++0x

# Input
SOURCES += fft4g.c
